version: '3.1'
services:
  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    volumes:
      - /docker-volumes/activemq-data:/data
      - /docker-volumes/activemq-log:/var/log/activemq
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'true'
      ACTIVEMQ_ENABLED_AUTH: 'true'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: 1234
      ACTIVEMQ_OWNER_LOGIN: 'onexas'
      ACTIVEMQ_OWNER_PASSWORD: 1234
  mariadb:
    image: mariadb:10.3.8
    ports:
      - 3306:3306
    volumes:
      - /docker-volumes/mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      
