######################################################################## 
##  This is the general config file of coordinate base application         ## 
########################################################################

###
## Sets profiles
###
spring.profiles.active: disable-entity

###
## Define node name
###
coordinate.node: ${AXES_NODE_NAME:axes-node1}

###  
## Define web server
###
server:
  port: ${AXES_SERVER_PORT:8080}
  servlet.session.timeout: ${AXES_SERVER_SESSION_TIMEOUT:30m}
  ssl:
    enabled: ${AXES_SERVER_SSL_ENABLED:false}
    key-store-type: ${AXES_SERVER_SSL_KEY_STORE_TYPE:null}
    key-store: ${AXES_SERVER_SSL_KEY_STORE_FILE:null}
    key-store-password: ${AXES_SERVER_SSL_KEY_STORE_PASSWORD:null}
    key-alias: ${AXES_SERVER_SSL_KEY_STORE_KEY_ALIAS:null}   
  
###
## Define default datasource for common usage, such as http session store.
### 
spring.datasource:
  jdbc-url: ${AXES_JDBC_URL:jdbc:mariadb://localhost:3306/axes}
  driver-class-name: ${AXES_JDBC_DRIVER:org.mariadb.jdbc.Driver}
  username: ${AXES_JDBC_USER:db-account}
  password: ${AXES_JDBC_PASSWORD:db-password}
  connectionTimeout: ${AXES_JDBC_CONNECTION_TIMEOUT:30000}
  maxLifetime: ${AXES_JDBC_MAX_LIFETIME:540000}
  maximumPoolSize: ${AXES_JDBC_MAX_POOL_SIZE:10}

spring.session.jdbc:
  initialize-schema: ${AXES_SESSION_JDBC_INITIALIZE_SCHEMA:always}
  schema: ${AXES_SESSION_JDBC_SCHEMA:classpath:schema/axes-web-session-init-mariadb.sql}  
  table-name: ${AXES_SESSION_JDBC_TABLE_NAME:AXE_SESSION}
  

###
## Define Coordinate Api url
###        
coordinate.api-base-path: ${COORDINATE_API_BASE_PATH:http://localhost:8088}
coordinate.api-disable-ssl-verify: ${COORDINATE_API_DISABLE_SSL_VERIFY:false}
coordinate.api-proxy-host: ${COORDINATE_API_PROXY_HOST:#{null}}
coordinate.api-proxy-port: ${COORDINATE_API_PROXY_PORT:#{null}}